### ISSUE TITLE
Inconsistency in find functionality

### ISSUE THREAD

**Issue by Rikko1204** [AY2324S2-CS2103T-T15-2/tp#134]
For instance, `find e/joh` will find the person but `find n/Bern` will not find the person

![Screenshot 2024-04-03 144624](https://github.com/AY2324S2-CS2103T-T15-2/tp/assets/64249290/12ab5fed-01e1-4550-a079-4d2554c2a07d)

**Comment by RingoftheKing** [comment]
Already stated in User Guide that name matching only matches WHOLE key words.

![image](https://github.com/AY2324S2-CS2103T-T15-2/tp/assets/90739493/92553787-32c9-47b6-a6b9-67e56538e022)
