### ISSUE TITLE
[PE-D][Tester A] user guide name 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-2/tp#162]
![image.png](https://raw.githubusercontent.com/ChocoRagdoll/ped/main/files/e5d4c6ac-aa13-437e-9052-7f0a1157de07.png)
The user guide' name has an extra . in it

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ChocoRagdoll/ped#1

**Comment by RingoftheKing** [comment]
Release correctly ig
