### ISSUE TITLE
[PE-D][Tester A] Extra flag

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-2/tp#164]
![image.png](https://raw.githubusercontent.com/ChocoRagdoll/ped/main/files/7397b7c0-fc1b-4798-8e4f-856826cf4e63.png)
when an unrecognized flag is added, the app doesn't account for it as a flag and from the message I will not understand which part of my command is wrong 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ChocoRagdoll/ped#3

**Comment by hjuntan** [comment]
We do not check for extra unrecognized flags, as it might be included in people names: ` Muhammad S/O Ahmad`, group names: `code/design lab` etc

**Comment by RingoftheKing** [comment]
same as #202
