### ISSUE TITLE
[PE-D][Tester B] Storage not functioning as required 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-2/tp#183]
Storage seems to be not updating and disappearing when I restart the app. As seen from the screenshot, after trying out commands on the sample json data such as editing and adding new people to the contact list, I closed the application and reopened it to see this screen. When I call view command, I get an empty screen too.

![image.png](https://raw.githubusercontent.com/chewbum/ped/main/files/fc95d79a-6ef9-44c3-a252-e7864dae8c6f.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: chewbum/ped#1

**Comment by hjuntan** [comment]
Similar issue to issue #187
