### ISSUE TITLE
[PE-D][Tester D] Save data does not load after exit

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-2/tp#187]
![Screenshot 2024-04-05 at 4.39.20 PM.png](https://raw.githubusercontent.com/meowwtama/ped/main/files/9e6349f9-7404-45d2-ac44-8415dddb9ee9.png)

Upon using the exit command, rerunning the application does not reload the previously saved data.
This makes the app useless. I am not able to store user data.

![Screenshot 2024-04-05 at 4.41.28 PM.png](https://raw.githubusercontent.com/meowwtama/ped/main/files/8596073e-4062-4f67-9c38-bcfeaf8b6d83.png)

Here is the error message encountered in my terminal, hope it helps!

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: meowwtama/ped#9

**Comment by RingoftheKing** [comment]
The error message seems to state that a date format that was allowed as input, wasn't able to be serialized and read correctly, thus causing failure, might want to check the JsonAdaptedPerson file

**Comment by hjuntan** [comment]
Solved by pr #240
