### ISSUE TITLE
[PE-D][Tester E] Mismatch in group name in delete command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-2/tp#190]
Group name and delete command do not match up. The command states CS2103T but the description says CS2013-T15

![image.png](https://raw.githubusercontent.com/whelan-low/ped/main/files/d7a2dd9c-e291-42ea-b9d3-ee1023d076b7.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: whelan-low/ped#5

**Comment by RingoftheKing** [comment]
fixed here

![image](https://github.com/AY2324S2-CS2103T-T15-2/tp/assets/90739493/89171d1a-a540-4c3b-91b7-88216483c780)
