### ISSUE TITLE
[PE-D][Tester B] Conflicting expectations in UG for Find Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-2/tp#191]
As stated at the top of the UG, square brackets parameters are deemed as optional parameters. Hence, in this scenario, technically find command should work fine on its own but it is instead throwing an error. 

![image.png](https://raw.githubusercontent.com/chewbum/ped/main/files/f4666941-4c8d-4e24-9b75-e9149b151e57.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chewbum/ped#3

**Comment by cheahTJ** [comment]
Put as a `Tip` saying that there needs to be `at least 1 identifier` specified for this command to work.
