### ISSUE TITLE
[PE-D][Tester A] Tagging as a separate command 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-2/tp#201]
![image.png](https://raw.githubusercontent.com/ChocoRagdoll/ped/main/files/0d277979-12de-4b25-95b2-6bb784900cb8.png)

currently, the group command is used repeatedly for both grouping and tagging. as a user, I may want a separate command for tagging since the functionality is primarily different from grouping. The current implementation may seem a bit confusing for the general users 

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: ChocoRagdoll/ped#12

**Comment by RingoftheKing** [comment]
Since the command already allows for grouping by just the tag, it is unnecessary to craft a new command. Although, id is not optional and the UG needs to be updated

**Comment by RingoftheKing** [comment]
May put under planned enhancements
