### ISSUE TITLE
[PE-D][Tester C] Invalid email format is getting accepted for add/edit commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-2/tp#205]
Currently the application accepts any input in the email as long as there's `@`.

input: `add id/E1234560 n/John Doe p/98765432 e/777@888 t/Student`
output:

![image.png](https://raw.githubusercontent.com/lokidoki102/ped/main/files/a2f9f45e-309a-4f51-a26e-d5122a998583.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: lokidoki102/ped#8

**Comment by cheahTJ** [comment]
This will not be rectified as according to the FAQ:

`This is not considered 'incorrect' (giving more freedom to the user is not necessarily incorrect) unless those unsuitable values causes the application to misbehave.` 

However, I will add to the UG to seek user's help to key in the correct email domain.
