### ISSUE TITLE
[PE-D][Tester D] Edit command allows me to edit person name to a number

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-2/tp#214]
![Screenshot 2024-04-05 at 5.10.56 PM.png](https://raw.githubusercontent.com/meowwtama/ped/main/files/d6638b1c-39c3-4ea4-9405-19cb1a1d298b.png)

Name should not be allowed to be a number, invalid name format.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: meowwtama/ped#14

**Comment by cheahTJ** [comment]
Linked to #217

**Comment by cheahTJ** [comment]
This will not be rectified as some names can have numbers in their names.
