### ISSUE TITLE
[PE-D][Tester B] Bug in error message for add command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-2/tp#222]
There is a lack of spacing between the word contain and the word alphanumeric.

![image.png](https://raw.githubusercontent.com/chewbum/ped/main/files/3bb5e338-d65c-4adb-832a-e5c3a458973f.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chewbum/ped#12

**Comment by RingoftheKing** [comment]
Fixed
