### ISSUE TITLE
[PE-D][Tester C] UI bug when resized to smaller screen

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-2/tp#223]
The tags for "Professor" and "Student" can only be read partially.

![image.png](https://raw.githubusercontent.com/lokidoki102/ped/main/files/2bf0c7fd-eb30-46b2-96ee-bd67a1add4d9.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lokidoki102/ped#10

**Comment by hjuntan** [comment]
Added planned enhancement in ug to tag not properly shown in pr #240
